Fix merge conflict in spotifyAuth.js and .env
yyee@yyee MINGW64 ~/Desktop/FYPproject (master)
$ git pull origin master --rebase
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 20 (delta 15), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (20/20), 4.28 KiB | 112.00 KiB/s, done.
From github.com:yyeeeeeeeeee/fyp-web-app
 * branch              master     -> FETCH_HEAD
   b45a74c1..228bb612  master     -> origin/master
CONFLICT (rename involved in collision): rename of node/src/.env -> node/.env has content conflicts AND collides with another path; this may result in nested conflict markers.
Auto-merging node/.env
CONFLICT (add/add): Merge conflict in node/.env
Auto-merging node/src/.env
Auto-merging node/src/api/routes/spotifyAuth.js
CONFLICT (content): Merge conflict in node/src/api/routes/spotifyAuth.js
error: could not apply 6019f6d7... Updated commit
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Could not apply 6019f6d7... Updated commit

yyee@yyee MINGW64 ~/Desktop/FYPproject (master|REBASE 1/1)
$ git push -u origin master
To github.com:yyeeeeeeeeee/fyp-web-app.git
 ! [rejected]          master -> master (non-fast-forward)
error: failed to push some refs to 'github.com:yyeeeeeeeeee/fyp-web-app.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
yyee@yyee MINGW64 ~/Desktop/FYPproject (master)
$ git pull origin master --rebase
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 20 (delta 15), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (20/20), 4.28 KiB | 112.00 KiB/s, done.
From github.com:yyeeeeeeeeee/fyp-web-app
 * branch              master     -> FETCH_HEAD
   b45a74c1..228bb612  master     -> origin/master
CONFLICT (rename involved in collision): rename of node/src/.env -> node/.env has content conflicts AND collides with another path; this may result in nested conflict markers.
Auto-merging node/.env
CONFLICT (add/add): Merge conflict in node/.env
Auto-merging node/src/.env
Auto-merging node/src/api/routes/spotifyAuth.js
CONFLICT (content): Merge conflict in node/src/api/routes/spotifyAuth.js
error: could not apply 6019f6d7... Updated commit
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Could not apply 6019f6d7... Updated commit

yyee@yyee MINGW64 ~/Desktop/FYPproject (master|REBASE 1/1)
$ git push -u origin master
To github.com:yyeeeeeeeeee/fyp-web-app.git
 ! [rejected]          master -> master (non-fast-forward)
error: failed to push some refs to 'github.com:yyeeeeeeeeee/fyp-web-app.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.